server:
  port: 8080 # 내장 톰캣 포트번호

application:
  url: https://zarit.store

spring:
  application:
    name: zarit

  datasource:
    url: jdbc:mysql://localhost:3306/zarit?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: woori
    password: Zarit1234!

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

ai:
  api:
    url: https://factchat-cloud.mindlogic.ai/v1/api/openai/chat/completions
    key: ${AI_API_KEY:GxaSIs2YK5W5s0RHUPD5yfHd9CCOHsaf}

