server:
  port: 80 # 내장 톰캣 포트번호

spring:
  application:
    name: side-project-blog

  datasource:
    url: jdbc:mysql://localhost:3306/db_name?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: woori
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true